In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/IMDB Dataset.csv")

In [44]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [45]:
data = df.sample(n=300, random_state=1)

In [46]:
data.head()

review sentiment
26247  With No Dead Heroes you get stupid lines like ...  negative
35067  I thought maybe... maybe this could be good. A...  negative
34590  An elite American military team which of cours...  negative
16668  Ridiculous horror film about a wealthy man (Jo...  negative
12196  Well, if you are one of those Katana's film-nu...  positive

In [47]:
sent = data['review']
sentiment = data['sentiment']

In [5]:
sent[:5]

26247    With No Dead Heroes you get stupid lines like ...
35067    I thought maybe... maybe this could be good. A...
34590    An elite American military team which of cours...
16668    Ridiculous horror film about a wealthy man (Jo...
12196    Well, if you are one of those Katana's film-nu...
Name: review, dtype: object

In [10]:
print(len(sent[26247]))

1685


In [6]:
!pip install tensorflow

In [7]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [12]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size = 3000

In [13]:
ohe_rep = [one_hot(word,voc_size)for word in sent]
ohe_rep[:3]

[[362,
  2861,
  563,
  643,
  659,
  66,
  2404,
  131,
  1859,
  2586,
  941,
  1938,
  1233,
  1962,
  2971,
  1523,
  853,
  248,
  1999,
  2145,
  248,
  1999,
  641,
  182,
  653,
  209,
  2598,
  2341,
  873,
  1140,
  2978,
  2016,
  1127,
  1721,
  437,
  2245,
  1719,
  635,
  1274,
  89,
  1557,
  2341,
  716,
  2981,
  441,
  678,
  1328,
  401,
  132,
  2978,
  209,
  59,
  2736,
  2340,
  1765,
  1967,
  362,
  2736,
  782,
  1724,
  1866,
  2009,
  2245,
  873,
  2904,
  873,
  1421,
  1765,
  2082,
  209,
  1459,
  130,
  248,
  716,
  1578,
  1753,
  2341,
  2580,
  1682,
  530,
  2078,
  2447,
  2944,
  2810,
  504,
  2330,
  2703,
  2109,
  248,
  2667,
  362,
  2736,
  1765,
  971,
  635,
  41,
  873,
  2736,
  1952,
  1386,
  112,
  2245,
  1742,
  362,
  873,
  2123,
  1568,
  836,
  209,
  883,
  873,
  270,
  209,
  716,
  1658,
  2586,
  682,
  961,
  2858,
  716,
  502,
  2374,
  2473,
  1938,
  357,
  1245,
  182,
  209,
  2482,
  1976,
  2341,
  716,
  180,


In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
sent_length = 3000

In [18]:
pad_doc = pad_sequences(ohe_rep, padding='post', maxlen=sent_length)
pad_doc[:3]

array([[ 362, 2861,  563, ...,    0,    0,    0],
       [2447,  654,  196, ...,    0,    0,    0],
       [1721, 1958, 2768, ...,    0,    0,    0]], dtype=int32)

In [19]:
dim = 250

In [21]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length = sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 3000, 250)         750000    
                                                                 
Total params: 750000 (2.86 MB)
Trainable params: 750000 (2.86 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [26]:
model.predict(pad_doc)

10/10 [==============================] - 0s 46ms/step


array([[[ 3.5589162e-02,  2.5310267e-02, -3.8337469e-02, ...,
         -8.0240481e-03,  2.1598015e-02,  5.0260425e-03],
        [-6.7028403e-03,  4.3025043e-02,  2.6748385e-02, ...,
         -1.7420232e-02, -4.4744875e-02,  3.9141182e-02],
        [-4.3105602e-02, -4.2550135e-02, -3.6345910e-02, ...,
         -4.0307499e-02, -9.6058249e-03,  1.2710061e-02],
        ...,
        [ 3.4975041e-02,  1.0938682e-02, -4.3043565e-02, ...,
         -3.1797387e-02, -2.9214634e-02,  2.2528339e-02],
        [ 3.4975041e-02,  1.0938682e-02, -4.3043565e-02, ...,
         -3.1797387e-02, -2.9214634e-02,  2.2528339e-02],
        [ 3.4975041e-02,  1.0938682e-02, -4.3043565e-02, ...,
         -3.1797387e-02, -2.9214634e-02,  2.2528339e-02]],

       [[-4.7798183e-02, -1.4050007e-02, -2.0510091e-02, ...,
          1.4198098e-02,  2.7286973e-02, -1.2149464e-02],
        [-1.8482842e-02,  8.1533790e-03, -4.5857619e-02, ...,
         -3.5566799e-03, -8.9761391e-03,  3.4087267e-02],
        [-4.0714394e-02, 

In [24]:
vectors = model.predict(pad_doc)

10/10 [==============================] - 1s 144ms/step


In [31]:
print(len(vectors))

300


In [27]:
flattened_vectors = vectors.flatten()

In [28]:
flattened_vectors[:3]

array([ 0.03558916,  0.02531027, -0.03833747], dtype=float32)

In [32]:
print(len(flattened_vectors))

225000000


In [34]:
data.shape

(300, 2)

In [37]:
vectors.shape

(300, 3000, 250)

In [40]:
# Sample 3D array with shape (300, 3000, 250)
vectors = np.random.rand(300, 3000, 250)  # Replace with your actual data

# Use mean aggregation across the last two dimensions
aggregated_vectors = vectors.mean(axis=(1, 2)).reshape(-1, 1)

aggregated_vectors.shape

(300, 1)

In [48]:
# Replace the 'review' column with the new aggregated vectors
data['review'] = aggregated_vectors
data['other_column'] = sentiment

In [1]:
data.drop(columns=['other_column'])

NameError: name 'data' is not defined

In [55]:
data.shape

(300, 3)

In [53]:
data.shape

(300, 3)