In [1]:
!pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [5]:
voc_size = 750

In [6]:
ohe_rep = [one_hot(word, voc_size)for word in sent]
print(ohe_rep)

[[492, 72, 343, 102, 56, 677], [567, 157, 343, 483, 117, 193], [652, 65, 216, 642], [492, 626, 343, 44, 492, 653], [47, 228, 419, 343, 483, 117, 193], [676, 343, 483, 117, 514, 335]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 12
embed_doc = pad_sequences(ohe_rep,padding='pre', maxlen=sent_length)
print(embed_doc)

[[  0   0   0   0   0   0 492  72 343 102  56 677]
 [  0   0   0   0   0   0 567 157 343 483 117 193]
 [  0   0   0   0   0   0   0   0 652  65 216 642]
 [  0   0   0   0   0   0 492 626 343  44 492 653]
 [  0   0   0   0   0  47 228 419 343 483 117 193]
 [  0   0   0   0   0   0 676 343 483 117 514 335]]


In [11]:
dim = 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 12, 10)            7500      
                                                                 
Total params: 7500 (29.30 KB)
Trainable params: 7500 (29.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
embed_doc[0]

array([  0,   0,   0,   0,   0,   0, 492,  72, 343, 102,  56, 677],
      dtype=int32)

In [16]:
model.predict(embed_doc)

1/1 [==============================] - 0s 46ms/step


array([[[-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [-0.0150012 , -0.00591501, -0.00558291, -0.02095499,
          0.01246865, -0.01045091, -0.00398407, -0.03332569,
          0.02965761,  0.03806985],
        [ 0.04834432, -0.03957999, -0.02358586,  0.0